spring:
  application:
    name: LostarkConfigServer
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URI}
          ignore-local-ssh-settings: true
          search-paths: lostark-config
          private-key: ${CONFIG_SERVER_PRIVATE_KEY}
        encrypt:
          enabled: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: 8888

encrypt:
  key: ${CONFIG_SERVER_ENCRYPT_KEY}

# Logback 설정은 logback-spring.xml에서 관리
logging:
  config: classpath:logback-spring.xml